### ISSUE TITLE
Does not compile in Ubuntu 16.04

### ISSUE THREAD

**Issue by jochristian** [jumanjihouse/docker-duoauthproxy#68]
Hi,

Does not compile in Ubuntu 16.04.
Stops with this error message:

`x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c OpenSSL/crypto/crl.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/crl.o
OpenSSL/crypto/crl.c:6:23: error: static declaration of ‘X509_REVOKED_dup’ follows non-static declaration
 static X509_REVOKED * X509_REVOKED_dup(X509_REVOKED *orig) {
                       ^
In file included from /usr/include/openssl/ssl.h:156:0,
                 from OpenSSL/crypto/x509.h:17,
                 from OpenSSL/crypto/crypto.h:30,
                 from OpenSSL/crypto/crl.c:3:
/usr/include/openssl/x509.h:751:15: note: previous declaration of ‘X509_REVOKED_dup’ was here
 X509_REVOKED *X509_REVOKED_dup(X509_REVOKED *rev);
               ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:14: recipe for target 'pyopenssl' failed
make: *** [pyopenssl] Error 1
`

A simple fix for this or do I need to use an older version of Ubuntu?

**Comment by jochristian** [comment]
Sorry.. I realized I posted this in the wrong place

**Comment by jumanjiman** [comment]
@jochristian Did you figure out the native build on ubuntu?

iirc I originally patched around this (or a similar openssl) build error at commit jumanjihouse/docker-duoauthproxy@765a22f1a2d2d8eea7134e1db503a94ed265b65a
but Duo Authproxy 2.4.18 and above (released about a week ago) makes the pyopenssl patch unnecessary for openssl 1.0.2
